[programs.localnet]
cross_pile = "6urrPCjcrQ1xaxbAJGMTtvZfA9wbMqQbEArKnVUHhYTs"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = <Your Key Path Here>

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "mainnet"
[[test.validator.clone]]
address = "GxJJd3q28eUd7kpPCbNXGeixqHmBYJ2owqUYqse3ZrGS"
[[test.validator.clone]]
address = "DQFt5uWLeXQKfQkwuiojaGPgdF5bFa4hgDiS4HSFFadV"

